// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyKcbEhypHHl-quyBKWj-1VD1M4_zGLfc',
    appId: '1:283379330962:web:910fd512b16865a2f25b4b',
    messagingSenderId: '283379330962',
    projectId: 'delivery-pizza-app-271c0',
    authDomain: 'delivery-pizza-app-271c0.firebaseapp.com',
    databaseURL: 'https://delivery-pizza-app-271c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delivery-pizza-app-271c0.appspot.com',
    measurementId: 'G-R567KVKDH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcnCH8hZQDLF0TWpFF3nMggbTo6-AezkY',
    appId: '1:283379330962:android:03a76a850d92cb51f25b4b',
    messagingSenderId: '283379330962',
    projectId: 'delivery-pizza-app-271c0',
    databaseURL: 'https://delivery-pizza-app-271c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delivery-pizza-app-271c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOEB1xdskqRJD_6UX1OsffKpXbzaB6jjw',
    appId: '1:283379330962:ios:d751b993b52f4774f25b4b',
    messagingSenderId: '283379330962',
    projectId: 'delivery-pizza-app-271c0',
    databaseURL: 'https://delivery-pizza-app-271c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delivery-pizza-app-271c0.appspot.com',
    iosBundleId: 'com.example.deliveryPizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOEB1xdskqRJD_6UX1OsffKpXbzaB6jjw',
    appId: '1:283379330962:ios:d751b993b52f4774f25b4b',
    messagingSenderId: '283379330962',
    projectId: 'delivery-pizza-app-271c0',
    databaseURL: 'https://delivery-pizza-app-271c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delivery-pizza-app-271c0.appspot.com',
    iosBundleId: 'com.example.deliveryPizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyKcbEhypHHl-quyBKWj-1VD1M4_zGLfc',
    appId: '1:283379330962:web:910fd512b16865a2f25b4b',
    messagingSenderId: '283379330962',
    projectId: 'delivery-pizza-app-271c0',
    authDomain: 'delivery-pizza-app-271c0.firebaseapp.com',
    databaseURL: 'https://delivery-pizza-app-271c0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'delivery-pizza-app-271c0.appspot.com',
    measurementId: 'G-R567KVKDH1',
  );
}
